(require 'haskell)
(require 'haskell-mode)
(require 'haskell-indentation)
(add-hook 'emacs-lisp-mode-hook 'paredit-mode)
(add-hook 'haskell-mode-hook 'whitespace-mode)
(add-hook 'haskell-mode-hook 'haskell-indentation-mode)
(add-hook 'haskell-mode-hook 'interactive-haskell-mode)
(require 'magit)
(require 'helm-config)
(require 'helm-projectile)
(require 'ace-jump-mode)
(global-set-key (kbd "C-c SPC") 'ace-jump-mode)
(helm-mode 1)
(projectile-global-mode)
(setq projectile-completion-system 'helm)
(helm-projectile-on)
(global-undo-tree-mode)
